name: Build RootFS Image

on:
  workflow_dispatch:
    inputs:
      kernel_versions:
        description: 'Kernel versions'
        required: false
        default: '6.18,7.0'
        type: string
  push:
    branches:
      - main

env:
  HOSTNAME: raphael
  BOOT_IMG: xiaomi-k20pro-boot.img
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  SUPPRESS_DEPRECATION_WARNINGS: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        kernel_version: ${{ fromJson('["6.18", "7.0"]') }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y mmdebstrap debian-archive-keyring unzip wget

      - name: Download kernel packages and boot.img
        run: |
          mkdir -p xiaomi-raphael-debs_${{ matrix.kernel_version }}
          curl -sL -o xiaomi-raphael-debs_${{ matrix.kernel_version }}/linux-image-xiaomi-raphael.deb "https://github.com/GengWei1997/kernel-deb/releases/download/kernel-v${{ matrix.kernel_version }}/linux-image-xiaomi-raphael.deb"
          curl -sL -o xiaomi-raphael-debs_${{ matrix.kernel_version }}/linux-headers-xiaomi-raphael.deb "https://github.com/GengWei1997/kernel-deb/releases/download/kernel-v${{ matrix.kernel_version }}/linux-headers-xiaomi-raphael.deb"
          curl -sL -o xiaomi-raphael-debs_${{ matrix.kernel_version }}/firmware-xiaomi-raphael.deb "https://github.com/GengWei1997/kernel-deb/releases/download/kernel-v${{ matrix.kernel_version }}/firmware-xiaomi-raphael.deb"
          curl -sL -o xiaomi-k20pro-boot.img "https://github.com/GengWei1997/kernel-deb/releases/download/v1.0.0/xiaomi-k20pro-boot.img"

      - name: Execute build
        run: |
          chmod +x build.sh
          sudo ./build.sh "tinyboot-iphoneos" "${{ matrix.kernel_version }}"

      - name: Compress image
        run: |
          FILENAME="rootfs-tinyboot-iphoneos-${{ matrix.kernel_version }}"
          7z a "${FILENAME}.7z" rootfs.img xiaomi-k20pro-boot.img

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ format('rootfs-tinyboot-iphoneos-{0}', matrix.kernel_version) }}
          path: "*.7z"
